# Generated by Django 3.1 on 2020-08-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='music_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업뎃 된 날짜')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 날짜')),
                ('singer', models.CharField(max_length=128, verbose_name='가수명')),
                ('title', models.CharField(max_length=128, verbose_name='곡명')),
                ('category', models.CharField(blank=True, choices=[('JPOP', '제이팝'), ('POP', '팝송'), ('CLASSIC', '클래식'), ('ETC', '기타등등')], max_length=32, null=True, verbose_name='범주')),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '좋음'), (2, '매우 좋음'), (3, '고귀함')], default=1, null=True, verbose_name='곡 선호도')),
            ],
            options={
                'verbose_name_plural': '음악',
                'db_table': 'musics',
                'ordering': ['star_rating'],
                'managed': True,
            },
        ),
    ]
