# Generated by Django 3.1 on 2020-08-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='singer',
            field=models.CharField(default=None, max_length=128, verbose_name='가수명'),
            preserve_default=False,
        ),
    ]
