# Generated by Django 3.1 on 2020-08-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='play_list_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만들어진 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업뎃 된 날짜')),
                ('play_list_name', models.CharField(max_length=128, verbose_name='플레이리스트 이름')),
                ('music', models.ForeignKey(db_column='music_id', on_delete=django.db.models.deletion.CASCADE, related_name='music', to='api.music', verbose_name='곡')),
            ],
            options={
                'verbose_name_plural': '나의 플레이 리스트',
                'db_table': 'play_lists',
                'managed': True,
            },
        ),
    ]
